# Generated by Django 2.2.10 on 2020-03-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='isSpecial',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
