# Generated by Django 2.2.10 on 2020-03-15 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_pizza_totaltopping'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzaType', models.CharField(choices=[('R', 'regular'), ('S', 'sicilian')], max_length=1)),
                ('pizzaSize', models.CharField(choices=[('s', 'small'), ('l', 'large')], max_length=1)),
                ('isSpecial', models.BooleanField(blank=True, default=False)),
                ('totalTopping', models.IntegerField(default=0)),
                ('pizzaPrice', models.DecimalField(decimal_places=2, max_digits=4)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pizzaTopping', models.ManyToManyField(blank=True, to='orders.Topping')),
            ],
        ),
    ]
