# Generated by Django 2.2.10 on 2020-03-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_customerpizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pastaOrdered',
            field=models.ManyToManyField(blank=True, to='orders.Pasta'),
        ),
        migrations.AddField(
            model_name='cart',
            name='platterOrdered',
            field=models.ManyToManyField(blank=True, to='orders.Platter'),
        ),
        migrations.AddField(
            model_name='cart',
            name='saladOrdered',
            field=models.ManyToManyField(blank=True, to='orders.Salad'),
        ),
        migrations.CreateModel(
            name='CustomerSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subSize', models.CharField(choices=[('s', 'small'), ('l', 'large')], max_length=1)),
                ('subName', models.CharField(max_length=64)),
                ('subPrice', models.DecimalField(decimal_places=2, max_digits=4)),
                ('subTopping', models.ManyToManyField(blank=True, to='orders.Topping')),
            ],
        ),
    ]
