# Generated by Django 2.2.10 on 2020-03-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200316_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersub',
            name='extraCheese',
            field=models.BooleanField(default=False),
        ),
    ]
