# Generated by Django 2.2.10 on 2020-03-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_customerpasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pastaOrdered',
            field=models.ManyToManyField(blank=True, to='orders.CustomerPasta'),
        ),
    ]
