# Generated by Django 2.2.10 on 2020-03-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200317_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSalad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saladName', models.CharField(max_length=64)),
                ('saladPrice', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='saladOrdered',
            field=models.ManyToManyField(blank=True, to='orders.CustomerSalad'),
        ),
    ]
